# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/pixel-extra-files/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),pixel-extra-files)

endif
