# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/pixel-extra-files/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/pixel-extra-files

PRODUCT_COPY_FILES += \
    vendor/google/pixel-extra-files/proprietary/system/etc/sysconfig/pixel_2016_exclusive.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/pixel_2016_exclusive.xml \
    vendor/google/pixel-extra-files/proprietary/system/etc/sysconfig/pixel_experience.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/pixel_experience.xml
